---

- hosts: all
  become: true
  tasks:


  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 and php packages
    tags: apache,apache2,ubuntu
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
#      update_cache: yes
#    when: ansible_distribution == "Ubuntu"
  - name: copy default html file for site
    tags: apache,apache2
    copy:
       src: default_site.html
       dest: /var/www/html/index.html
       owner: root
       group: root
       mode: 0644

- hosts: db_servers
  become: true
  tasks: 

  - name: install mariadb-server
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server 
      state: latest
   # when: ansible_distribution == "Ubuntu"
 
