---

- hosts: Tomcat4

  become: yes
  tasks:
  
  - name: Update apt packages
    apt:
    #  upgrade: true
      update_cache: true

  - name: create /opt/tomcat directory
    file:
      path: /opt/tomcat
      state: directory
      mode: 0755

  - name: download & unarchive
    unarchive:
      src: https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.23/bin/apache-tomcat-10.0.23.tar.gz
      dest: /opt/tomcat
      remote_src: yes
      extra_opts: [--strip-components=1]

  - name: Make sure a service is running
    ansible.builtin.systemd:
      state: started
      enabled: true
      name: tomcat.service

  - name: Copy Tomcat service from local to remote
    copy:
       src: tomcat.service
       dest: /etc/systemd/system/
       mode: 0755
#       remote_src: no
#  - name: start tomcat services
#      shell: nohup /usr/local/apache-tomcat-9.0.44/bin/startup.sh


  - name: Start and enable Tomcat service
    systemd:
      name: tomcat
      state: started
      enabled: true
      daemon_reload: true


